services:  
  app_dev:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev 
    networks:
      hispanie_backend_hispanie_bridge:
        ipv4_address: 169.254.10.4
        aliases:
          - "hispanie-frontend.app"
    ports:
      - 3202:3202  
    volumes:
      - ./:/app/
      - /app/node_modules

  nginx:
    image: nginx:latest
    networks:
      hispanie_backend_hispanie_bridge:
        ipv4_address: 169.254.10.5
        aliases:
          - "hispanie-frontend.proxy"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./resources/nginx_dev_ssl.conf:/etc/nginx/conf.d/ssl.conf
      - ./resources/ssl/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./resources/ssl/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
      - ./resources/ssl/dhparam.pem:/etc/ssl/certs/dhparam.pem
    depends_on:
      - app_dev

networks:
  hispanie_backend_hispanie_bridge:
    external: true